services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '12345678'
      PGPASSWORD: '12345678'
      POSTGRES_DB: korint_database
      POSTGRES_DATABASE: korint_database
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=korint_database
      - POSTGRES_DATABASE=korint_database
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
volumes:
  db-data:
